name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

    - name: Install dependencies
      run: pip install -r requirements.txt
        pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py
