name: Update data v2

on:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '02 */2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Update data 
        run: python update.py
        env:
          PROXY_SERVERS: ${{ secrets.PROXY_SERVERS }}

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date +%FT%T%z)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
